### ISSUE TITLE
Add "Open search results in Jira" option to `ja` keyword

### ISSUE THREAD

**Issue by atoftegaard-git** [rwilgaard/alfred-jira-search#8]
**Is your feature request related to a problem? Please describe.**
I'm missing a quick way to see my assigned issues in a Jira search.

**Describe the solution you'd like**
The option to open search results in Jira with the `js` keyword (Hold down `ctrl`), would be nice to have with the `ja` keyword as well, to get a better overview of one's own issues.

**Comment by rwilgaard** [comment]
Added in v1.1.0
